version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: econetra-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ../backend
    container_name: econetra-backend
    env_file:
      - ../backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  frontend:
    build: ../frontend
    container_name: econetra-frontend
    env_file:
      - ../frontend/.env
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data:
